### ISSUE TITLE
clustermq package missing

### ISSUE THREAD

**Issue by mschubert** [eddelbuettel/ctv-hpc#12]
Hi,

I [asked a while ago](https://github.com/eddelbuettel/ctv-hpc/pull/10) to add the [clustermq](https://cran.r-project.org/web/packages/clustermq/index.html) package to HPC task view.

Looking for it now, I can see it in [HighPerformanceComputing.ctv](https://github.com/eddelbuettel/ctv-hpc/blob/master/HighPerformanceComputing.ctv), but not on the [web page](https://cran.r-project.org/web/views/HighPerformanceComputing.html).

Can you please take a look why it isn't there?

Thank you!

**Comment by eddelbuettel** [comment]
Weird. It is rare that Achim (in his svn repo) and I (here) cross paths but looks like it happened.

Re-sync the git repo with his (removing two packages) and pushed to svn as r2815.  Should be visible at CRAN the next time he syncs.

(And maybe email / reopen existing pr instead of new issue?  Anyway, it got me to make the change you needed so all good for you I suppose ;-)  )

**Comment by mschubert** [comment]
Thank you!

(As far as I know you can not re-open merged PRs. I will comment there next time, but as the package was listed on the web before this was a new issue for me.)

**Comment by eddelbuettel** [comment]
Correct. "reopen" was the wrong verb, you cannot.  But you can still _comment_ there and I get the same notification.  So in that sense (as we actually dropped the ball on that initial request) it would have been fine too.   Anyway ...   ;-)
